name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd ~
            if [ ! -d "app" ]; then
              git clone https://github.com/A1haaydarr/web.git app
            fi
            cd app
            git pull origin main
            docker build -t my-website .
            docker stop web || true
            docker rm web || true
            docker run -d -p 80:80 --name web my-website
